
import __ASTRO_IMAGE_IMPORT_Z12T7h4 from "../../../public/static/1200x630.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fproject-b.md";
import __ASTRO_IMAGE_IMPORT_Z12Tfhr from "../../../public/static/1200x630.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fproject-a.md";
import __ASTRO_IMAGE_IMPORT_Z12SYgG from "../../../public/static/1200x630.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fproject-c.md";
import __ASTRO_IMAGE_IMPORT_Z15fAKA from "./assets/openpage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbbctf2025%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZrjRtV from "./assets/logo.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fumcsctf2025-prelim%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z1uTxEG from "./assets/logo.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fumcsctf2025-finals%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZV0STn from "./assets/1200x630.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fuvtctf2025%2Findex.mdx";
export default new Map([["../../../public/static/1200x630.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fproject-b.md", __ASTRO_IMAGE_IMPORT_Z12T7h4], ["../../../public/static/1200x630.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fproject-a.md", __ASTRO_IMAGE_IMPORT_Z12Tfhr], ["../../../public/static/1200x630.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fproject-c.md", __ASTRO_IMAGE_IMPORT_Z12SYgG], ["./assets/openpage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbbctf2025%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z15fAKA], ["./assets/logo.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fumcsctf2025-prelim%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZrjRtV], ["./assets/logo.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fumcsctf2025-finals%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z1uTxEG], ["./assets/1200x630.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fuvtctf2025%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZV0STn]]);
		